name: Lint

on:
  push:
    branches: [master]
    paths:
    - src/**
  pull_request:
    types: [opened, synchronize]
    paths:
    - src/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: install
        run: npm install 
      - name: lint
        run: npm run lint
      - name: prettier
        run: npm run prettier